import Head from 'next/head';
import Job from '@containers/Job';
import { useRouter } from 'next/router';

const WorkForm = () => {
  const { query } = useRouter();
  const { job } = query;

  return (
    <>
      <Head>
        <title>Apply for a job - {job} | Joe Bar Business Solutions</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='images/favicon-32x32.ico' />
      </Head>
      <main>
        <Job job={job} />
      </main>
    </>
  );
};

export default WorkForm;
