import Head from 'next/head';
import Apply from '@containers/Apply';
import WhatsAppButton from '@components/WhatsAppButton';

const ApplyHome = () => {
  return (
    <>
      <Head>
        <title>Apply for a job | Joe Bar Business Solutions</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='images/favicon-32x32.ico' />
      </Head>
      <main>
        <Apply />
        <WhatsAppButton />
      </main>
    </>
  );
};

export default ApplyHome;
