import Head from 'next/head';
import Apply from '@containers/Apply';

export default function Home() {
  return (
    <>
      <Head>
        <title>Joe Bar Business Solutions | Apply for a job</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='images/favicon-32x32.ico' />
      </Head>
      <main>
        <Apply />
      </main>
    </>
  );
}
